/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../public/model.gltf -T -i -s --precision 4 
Files: ../public/model.gltf [257.98KB] > model-transformed.glb [19.1MB] (-7305%)
*/

import React, { useRef, useState } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { useThree, Canvas } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  const meshRef = useRef()
  const [hovered, setHovered] = useState(false);


  const onPointerOver = () => {
    setHovered(true);
  }

  const onPointerOut = () => {
    setHovered(false);
  }

  const handleMeshHover = (e, hover) => {
    e.material.emissive.set(hover ? '0xaaaaaa' : '0x000000');
    setHovered(hover);
  }



  const handleMeshClick = () => {
    window.open('https://github.com/mo-ai-source/Carter_Drill', '_blank');  // Opens the  file in a new tab
  };
  const handleMeshClick2 = () => {
    window.open('https://www.linkedin.com/in/mohamed-yusuf-07a426209/', '_blank');  // Opens the HTML file in a new tab
  };
  const handleMeshClick3 = () => {
    window.open('https://github.com/mo-ai-source/Twitter', '_blank');  // Opens the HTML file in a new tab
  };
  


  return (
    <group {...props} dispose={null}>
      <directionalLight intensity={6} decay={2} color="#fff9e6" position={[1.4774, 19.6795, -16.1027]} rotation={[-2.2329, 0.0274, 0.149]} />
      <pointLight intensity={25.4239} decay={2} position={[0.0374, 2.5918, -1.1891]} rotation={[-Math.PI / 2, 0, 0]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={50.7485} position={[-0.0351, 1.2946, 0.3592]} rotation={[0.0516, 0.0517, -0.0141]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={39.5978} position={[0.5559, 1.494, 1.6942]} rotation={[-0.1132, 0.7304, 0.0643]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={39.5978} position={[-1.0104, 1.4929, 1.3655]} rotation={[-0.0204, -0.8296, -0.0264]} />
      <pointLight intensity={50.4239} decay={2} position={[0.0877, 2.5577, 1.6293]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh castShadow receiveShadow geometry={nodes.mouse_pad.geometry} material={materials.PaletteMaterial001} position={[0.7831, 0.7713, -0.4065]} rotation={[-Math.PI, 0.2139, -Math.PI]} scale={[-0.1467, -0.0006, -0.1467]} />
      <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.0355, 2.628, 1.5987]} scale={[0.0581, 0.033, 0.0581]} />
      <group position={[-1.327, 0.9422, 0.2007]} rotation={[-2.7653, 0.0437, -1.9734]} scale={[0.2108, 0.2075, 0.2089]}>
      <mesh 
          ref={meshRef} 
          onClick={handleMeshClick} 
          onPointerOver={(e) => handleMeshHover(e, true)} 
          onPointerOut={(e) => handleMeshHover(e, false)}
          castShadow 
          receiveShadow 
          geometry={nodes.Mesh011.geometry} 
          material={materials['lambert1.001']}/>
        <mesh castShadow receiveShadow geometry={nodes.Mesh011_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.room_1.geometry} material={materials['Material.010']} position={[0.9707, 1.2646, -2.3202]} scale={[-0.356, -1.0601, -0.3406]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube027.geometry} material={materials['Material.006']} position={[-1.3295, 1.5682, -0.5341]} rotation={[0, 0, -Math.PI]} scale={[-0.1363, -0.0106, -1.4837]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials['Material.008']} position={[0.8871, 0.6779, -1.448]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.2774, 0.0405, 0.3245]} />
      <group position={[-1.2083, 1.0204, 0.8312]} rotation={[1.484, -0.3521, 1.8482]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh008.geometry} material={materials.leaf_01} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh008_1.geometry} material={materials.rose} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh008_2.geometry} material={materials.PaletteMaterial004} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh008_3.geometry} material={materials.PaletteMaterial005} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh008_4.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.photoframe.geometry} material={materials['Material.014']} position={[-0.164, 1.6303, -2.702]} rotation={[0.4948, -1.5587, 0.4966]} scale={[0.0259, 1.0331, 0.673]} />
      <mesh castShadow receiveShadow geometry={nodes.CUSHION.geometry} material={materials.CUSHION} position={[-0.1558, 0.5625, -2.2898]} scale={[0.6605, 0.0395, 0.4036]} />
      <mesh castShadow receiveShadow geometry={nodes.pillow.geometry} material={materials['Material.012']} position={[-0.6486, 0.779, -2.3077]} rotation={[-0.3242, 0.8456, 0.2999]} scale={4.0636} />
      <mesh castShadow receiveShadow geometry={nodes.pillow001.geometry} material={materials['Material.011']} position={[-0.5576, 0.7272, -2.2125]} rotation={[-0.3478, 0.7584, 0.2554]} scale={3.1093} />
      <group position={[1.0218, 1.0647, -0.794]} rotation={[1.571, -0.1899, -1.5698]} scale={0.001}>
      <mesh 
        ref={meshRef} 
        onClick={handleMeshClick2} 
        onPointerOver={(e) => handleMeshHover(e, true)} 
        onPointerOut={(e) => handleMeshHover(e, false)}
        castShadow 
        receiveShadow 
        geometry={nodes.Mesh010.geometry} 
        material={materials.PaletteMaterial007} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh010_1.geometry} material={materials.PaletteMaterial009} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh010_2.geometry} material={materials.display} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh010_3.geometry} material={materials.camera} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh010_4.geometry} material={materials.aluminium} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh010_5.geometry} material={materials.PaletteMaterial006} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh010_6.geometry} material={materials.PaletteMaterial008} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Keyboard.geometry} material={materials['KeyboardKeys.001']} position={[0.7117, 0.7752, -0.9202]} rotation={[0.0033, -1.3531, 0.0032]} scale={0.0943} />
      <mesh castShadow receiveShadow geometry={nodes.Carpet01.geometry} material={materials['Bez názvu']} position={[-0.1399, 0.0029, 0.5683]} rotation={[0, -Math.PI / 2, 0]} scale={[3.9719, 0.4525, 2.9725]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube030.geometry} material={materials['photo (big)']} position={[0.0175, 1.7256, 2.7385]} rotation={[0, 0, -Math.PI]} scale={[-0.2819, -0.3728, -0.0067]} />
      <mesh castShadow receiveShadow geometry={nodes.Line023.geometry} material={materials.Material__608} position={[-1.0839, 0.7718, -0.4627]} rotation={[Math.PI / 2, 0, -0.2451]} scale={[0.0043, 0.0043, 0.0023]} />
      <mesh castShadow receiveShadow geometry={nodes.Line024.geometry} material={materials.Material__609} position={[-0.9485, 0.7718, -0.548]} rotation={[Math.PI / 2, 0, -0.9001]} scale={[0.0043, 0.0043, 0.0023]} />
      <mesh castShadow receiveShadow geometry={nodes.Line025.geometry} material={materials.Material__610} position={[-0.9485, 0.7219, -0.548]} rotation={[Math.PI / 2, 0, -0.9001]} scale={[0.0043, 0.0043, 0.0023]} />
      <mesh castShadow receiveShadow geometry={nodes.Line026.geometry} material={materials.Material__611} position={[-0.9485, 0.7718, -0.548]} rotation={[Math.PI / 2, 0, -0.9001]} scale={[0.0043, 0.0043, 0.0023]} />
      <mesh castShadow receiveShadow geometry={nodes.Line027.geometry} material={materials.Material__612} position={[-0.9987, 0.8223, -0.4955]} rotation={[Math.PI / 2, 0, -0.5799]} scale={[0.0043, 0.0043, 0.0023]} />
      <mesh castShadow receiveShadow geometry={nodes.Line028.geometry} material={materials.Material__613} position={[-1.3182, 1.5819, 1.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line029.geometry} material={materials.Material__615} position={[-1.3182, 1.5819, 1.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line030.geometry} material={materials.Material__614} position={[-1.3182, 1.5819, 1.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line031.geometry} material={materials.Material__616} position={[-1.3182, 1.5819, 1.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line032.geometry} material={materials.Material__619} position={[-1.3182, 1.5819, 1.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line033.geometry} material={materials.Material__620} position={[-1.3182, 1.5819, 1.033]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line034.geometry} material={materials.Material__621} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line035.geometry} material={materials.Material__622} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line036.geometry} material={materials.Material__623} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line037.geometry} material={materials.Material__624} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line038.geometry} material={materials.Material__625} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line039.geometry} material={materials.Material__626} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Line040.geometry} material={materials.Material__627} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh ref={meshRef} onClick={handleMeshClick3} castShadow receiveShadow geometry={nodes.Line041.geometry} material={materials.Material__628} position={[-1.3182, 1.5819, -0.3205]} rotation={[Math.PI / 2, 0, 0]} scale={0.0043} />
      <mesh castShadow receiveShadow geometry={nodes.Object021.geometry} material={materials.Material__41} position={[-1.0839, 0.7718, -0.4627]} rotation={[Math.PI / 2, 0, -0.2451]} scale={[0.0043, 0.0043, 0.0023]} />
      <group position={[0.8382, 0.7885, -1.5634]} scale={0.0077}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh001.geometry} material={materials.MT_PM_V53_Dendranthema_morifolium_01_Twig_01} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh001_1.geometry} material={materials.MT_PM_V53_Dendranthema_morifolium_01_Flower_01} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Clay_Vase_01.geometry} material={materials['Material #27']} position={[0.855, 0.7758, -1.5756]} scale={0.0077} />
      <group position={[0.8539, 0.7709, -1.5743]} scale={0.0077}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh005.geometry} material={materials['02 - Default']} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh005_1.geometry} material={materials.Codariocalyx_01} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh005_2.geometry} material={materials.Eucalyptus_01} />
      </group>
      <group position={[0.841, 1.0669, -1.5958]} scale={0.0077}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh002.geometry} material={materials.Filament_1} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_1.geometry} material={materials.pro_petal_01} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_2.geometry} material={materials.pro_petal_02} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_3.geometry} material={materials.pro_petal_03} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh002_4.geometry} material={materials.Filament_2} />
      </group>
      <mesh  castShadow receiveShadow geometry={nodes.base.geometry} material={materials.PaletteMaterial010} position={[1.0438, 0.7777, 0.5621]} rotation={[Math.PI / 2, 0, 0.3857]} scale={0.01} />
      <mesh castShadow receiveShadow geometry={nodes.filament.geometry} material={materials.PaletteMaterial011} position={[0.8727, 1.2044, 0.4926]} rotation={[Math.PI / 2, 0, 0.3857]} scale={0.01} />
      <instancedMesh args={[nodes.Cube015.geometry, materials['Material.006'], 13]} castShadow receiveShadow instanceMatrix={nodes.Cube015.instanceMatrix} />
      <instancedMesh args={[nodes.Cube023.geometry, materials.PaletteMaterial001, 10]} castShadow receiveShadow instanceMatrix={nodes.Cube023.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
